---
- name: Install packages for Docker Developers 
  hosts: all
  
  tasks:
     
    - name: Install 'yum-utils'
      yum:
        name: yum-utils 
        state: latest
  
    - name: Add repository 
      yum_repository:
        name: Docker-repo
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        enabled: yes
    
    - name: Enable test repositories 1
      command: yum-config-manager --enable docker-ce-nightly
    
    - name: Enable test repositories 2
      command: yum-utils --enable docker-ce-test
    
    - name: Install packages for Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        
    - name: Start service Docker
      systemd:
        name: docker
        state: started
