--- 
- name:
  hosts: all
  
  tasks:   
     - name: Install packages 
       yum: 
        name:
          - httpd 
          - epel-release
          - http://rpms.remirepo.net/enterprise/remi-release-8.rpm
          - yum-utils
          - mariadb-server
          - mariadb
          - git
        state: latest
     
     - name: Enable PHP remi
       command: yum-config-manager --enable remi-php74
       
     - name: Upgrade all packages
       yum: 
         name: '*'
         state: latest
     
     - name: Install php
       yum:
        name: 
           - php
           - php-mcrypt
           - php-cli
           - php-gd
           - php-curl
           - php-mysql
           - php-ldap
           - php-zip
           - php-fileinfo
           - php-fpm
        state: latest
         
     - name: Configure Firewalld 
       firewalld:
         service:
               - https
               - http
               - mysql
         permanent: yes
         state: enabled
     
     - name: Start Services 
       systemd:
          name:
             - httpd
             - mariadb
          state: started
